# Generated by Django 4.1 on 2022-08-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverphoto',
            field=models.ImageField(default='natural-cover-facebook.jpeg', upload_to='cover_images'),
        ),
    ]
