version: "3.8"

services:
  mysql-db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3325"

  backend:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file: .env
    restart: always
    volumes:
      - .:/social_book
    depends_on:
      - mysql-db
    working_dir: "/var/social_book"
    expose:
      - 80
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "127.0.0.0:8000"]

volumes:
  mysql_data: